USE EC1_CC1N;

SHOW COLUMNS FROM FORNECEDORES;
INSERT INTO FORNECEDORES(FORNEC_COD,FORNEC_NOME,FORNEC_RUA,FORNEC_NUMRUA,FORNEC_BAIRRO,
FORNEC_CIDADE,FORNEC_ESTADO,FORNEC_PAIS,FORNEC_CODPOSTAL,FORNEC_TELEFONE,FORNEC_CONTATO)
VALUES (1, 'Fornecedor A', 'Rua das Gaivotas', 78, 'Aurora', 'Belo Horizonte', 'Minas Gerais', 'Brasil', '30100-000', '(31) 98912-2543', 'João Cleber');

INSERT INTO FORNECEDORES(FORNEC_COD,FORNEC_NOME,FORNEC_RUA,FORNEC_NUMRUA,FORNEC_BAIRRO,
FORNEC_CIDADE,FORNEC_ESTADO,FORNEC_PAIS,FORNEC_CODPOSTAL,FORNEC_TELEFONE,FORNEC_CONTATO)
VALUES (2, 'Fornecedor B', 'Av. Brasil', 200, 'Zona Sul', 'Rio de Janeiro', 'RJ', 'Brasil', '20000-000', '(21) 99876-5432', 'Maria Oliveira');

INSERT INTO FORNECEDORES(FORNEC_COD,FORNEC_NOME,FORNEC_RUA,FORNEC_NUMRUA,FORNEC_BAIRRO,
FORNEC_CIDADE,FORNEC_ESTADO,FORNEC_PAIS,FORNEC_CODPOSTAL,FORNEC_TELEFONE,FORNEC_CONTATO)
VALUES (3, 'Fornecedor C', 'Rua das Flores', 50, 'Jardim', 'Curitiba', 'PR', 'Brasil', '80000-000', '(41) 91234-5678', 'Ana Paula');

INSERT INTO FORNECEDORES(FORNEC_COD,FORNEC_NOME,FORNEC_RUA,FORNEC_NUMRUA,FORNEC_BAIRRO,
FORNEC_CIDADE,FORNEC_ESTADO,FORNEC_PAIS,FORNEC_CODPOSTAL,FORNEC_TELEFONE,FORNEC_CONTATO)
VALUES (4, 'Fornecedor D', 'Av. Paulista', 1500, 'Bela Vista', 'São Paulo', 'SP', 'Brasil', '01310-100', '(11) 98123-4567', 'Carlos Santos');

INSERT INTO FORNECEDORES(FORNEC_COD,FORNEC_NOME,FORNEC_RUA,FORNEC_NUMRUA,FORNEC_BAIRRO,
FORNEC_CIDADE,FORNEC_ESTADO,FORNEC_PAIS,FORNEC_CODPOSTAL,FORNEC_TELEFONE,FORNEC_CONTATO)
VALUES (5, 'Fornecedor E', 'Rua dos Pinheiros', 300, 'Zona Norte', 'Fortaleza', 'CE', 'Brasil', '60000-000', '(85) 99876-1234', 'Fernanda Lima');

UPDATE FORNECEDORES SET FORNEC_NUMRUA = 78 WHERE FORNEC_COD = 3;

UPDATE FORNECEDORES SET FORNEC_CIDADE  = 'Niterói' WHERE FORNEC_COD = 2;

DELETE FROM FORNECEDORES WHERE FORNEC_COD = 5;


SHOW COLUMNS FROM FILIAIS;
INSERT INTO FILIAIS(FILIAL_COD,FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE,
 FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
 VALUES (1, 'Filial SP', 'Rua Exemplo', 101, 'Centro', 'São Paulo', 'SP', 'Brasil', '01001-001', 'Capacidade: 1000 unidades');
 
 INSERT INTO FILIAIS(FILIAL_COD,FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE,
 FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
 VALUES (2, 'Filial RJ', 'Av. Atlântica', 500, 'Copacabana', 'Rio de Janeiro', 'RJ', 'Brasil', '22000-002', 'Capacidade: 800 unidades');
 
 INSERT INTO FILIAIS(FILIAL_COD,FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE,
 FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
 VALUES (3, 'Filial PR', 'Rua das Araucárias', 75, 'Jardim Botânico', 'Curitiba', 'PR', 'Brasil', '80001-003', 'Capacidade: 600 unidades');
 
 INSERT INTO FILIAIS(FILIAL_COD,FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE,
 FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
 VALUES (4, 'Filial CE', 'Av. Beira Mar', 1200, 'Meireles', 'Fortaleza', 'CE', 'Brasil', '60001-004', 'Capacidade: 700 unidades');
 
 INSERT INTO FILIAIS(FILIAL_COD,FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE,
 FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
 VALUES (5, 'Filial MG', 'Av. Afonso Pena', 900, 'Centro', 'Belo Horizonte', 'MG', 'Brasil', '30100-005', 'Capacidade: 500 unidades');
 
 UPDATE FILIAIS SET FILIAL_CAPACIDADE = 20.000 WHERE FILIAL_COD = 3;
 
 UPDATE FILIAIS SET FILIAL_NUMRUA = 29 WHERE FILIAL_COD = 5;
 
 DELETE FROM FILIAIS WHERE FILIAL_COD = 2;
 
 
 SHOW COLUMNS FROM PRODUTOS;
INSERT INTO PRODUTOS(PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (1, 'Produto A', 'Descrição Produto A', 'Especificação A', 500.000, 25.00, 'UN', 50.000);

INSERT INTO PRODUTOS(PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (2, 'Produto B', 'Descrição Produto B', 'Especificação B', 300.000, 40.00, 'KG', 30.000);

INSERT INTO PRODUTOS(PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (3, 'Produto C', 'Descrição Produto C', 'Especificação C', 200.000, 15.00, 'LT', 20.000);

INSERT INTO PRODUTOS(PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (4, 'Produto D', 'Descrição Produto D', 'Especificação D', 100.000, 50.00, 'UN', 10.000);

INSERT INTO PRODUTOS(PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (5, 'Produto E', 'Descrição Produto E', 'Especificação E', 150.000, 35.00, 'KG', 15.000);

UPDATE PRODUTOS SET PROD_QUANT = 50.000 WHERE PROD_COD = 3;

UPDATE PRODUTOS SET PROD_ESTOQ_MIN = 25.000 WHERE PROD_COD = 4;

DELETE FROM PRODUTOS WHERE PROD_COD = 5;


SHOW COLUMNS FROM PEDIDOS;
INSERT INTO PEDIDOS(PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (1, '2024-11-01', '10:30:00', '2024-11-10', 'PENDENTE', 1);

INSERT INTO PEDIDOS(PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (2, '2024-11-02', '11:00:00', '2024-11-12', 'CONCLUÍDO', 2);

INSERT INTO PEDIDOS(PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (3, '2024-11-03', '12:00:00', '2024-11-13', 'EM ESPERA', 3);

INSERT INTO PEDIDOS(PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (4, '2024-11-04', '13:00:00', '2024-11-14', 'PENDENTE', 4);

INSERT INTO PEDIDOS(PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (5, '2024-11-05', '14:00:00', '2024-11-15', 'CONCLUÍDO', 1);

UPDATE PEDIDOS SET PED_STATUS = 'CONCLUÍDO' WHERE PED_CODIGO = 3;

UPDATE PEDIDOS SET PED_PREVISAO = '2024-12-20' WHERE PED_CODIGO = 4;

DELETE FROM PEDIDOS WHERE PED_CODIGO = 5;


SHOW COLUMNS FROM RECEBIMENTOS;
INSERT INTO RECEBIMENTOS( RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-06', '10:00:00', 50.000, 'Sem avarias', 1);

INSERT INTO RECEBIMENTOS( RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-07', '11:00:00', 75.000, 'Com avarias', 2);

INSERT INTO RECEBIMENTOS( RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-08', '12:00:00', 100.000, 'Perfeito estado', 3);

INSERT INTO RECEBIMENTOS( RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-09', '13:00:00', 25.000, 'Pequenos danos', 4);

INSERT INTO RECEBIMENTOS( RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-10', '14:00:00', 60.000, 'Sem problemas', 5)

UPDATE RECEBIMENTOS SET RECEB_CONDICAO = 'Com pequenos danos' WHERE RECEB_PEDIDOS = 2;

UPDATE RECEBIMENTOS SET RECEB_QUANT_PROD = 80.000 WHERE RECEB_PEDIDOS = 3;

DELETE FROM RECEBIMENTOS WHERE RECEB_PEDIDOS = 5;


INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (1, 1, 50.000);

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (1, 2, 30.000);

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (2, 1, 20.000);

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (3, 3, 15.000);

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (4, 4, 10.000);

UPDATE PEDIDOS_PRODUTOS SET PDPR_QUANT = 55.000 WHERE PDPR_PEDIDOS = 1 AND PDPR_PRODUTOS = 1;

UPDATE PEDIDOS_PRODUTOS SET PDPR_QUANT = 25.000 WHERE PDPR_PEDIDOS = 2 AND PDPR_PRODUTOS = 1;

DELETE FROM PEDIDOS_PRODUTOS WHERE PDPR_PEDIDOS = 1 AND PDPR_PRODUTOS = 1;


INSERT INTO FILIAIS_PRODUTOS(FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (1, 1, 200.000);

INSERT INTO FILIAIS_PRODUTOS(FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (1, 2, 150.000);

INSERT INTO FILIAIS_PRODUTOS(FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (2, 3, 100.000);

INSERT INTO FILIAIS_PRODUTOS(FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (3, 4, 75.000);

INSERT INTO FILIAIS_PRODUTOS(FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (4, 1, 50.000);

UPDATE FILIAIS_PRODUTOS SET FLPR_QUANT = 220.000 WHERE FLPR_FILIAL = 1 AND FLPR_PRODUTOS = 1;

UPDATE FILIAIS_PRODUTOS SET FLPR_QUANT = 80.000 WHERE FLPR_FILIAL = 3 AND FLPR_PRODUTOS = 4;

DELETE FROM FILIAIS_PRODUTOS WHERE FLPR_FILIAL = 4 AND FLPR_PRODUTOS = 1;


INSERT INTO FORNECEDORES_PRODUTOS(FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (1, 1);

INSERT INTO FORNECEDORES_PRODUTOS(FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (1, 2);

INSERT INTO FORNECEDORES_PRODUTOS(FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (2, 3);

INSERT INTO FORNECEDORES_PRODUTOS(FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (3, 4);

INSERT INTO FORNECEDORES_PRODUTOS(FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (4, 1);

UPDATE FORNECEDORES_PRODUTOS SET FRPR_FORNECEDOR = 2 WHERE FRPR_FORNECEDOR = 1 AND FRPR_PRODUTOS = 2;

UPDATE FORNECEDORES_PRODUTOS SET FRPR_PRODUTOS = 3 WHERE FRPR_FORNECEDOR = 3 AND FRPR_PRODUTOS = 4;

DELETE FROM FORNECEDORES_PRODUTOS WHERE FRPR_FORNECEDOR = 4 AND FRPR_PRODUTOS = 1;
